name: polymer_ajax_backed_model_behavior
version: 0.0.1
description: A native Dart Polymer behavior providing wiring for elements with an ajax provided model.
author: Mike Hoolehan <mike@hoolehan.com>
homepage: https://github.com/ilikerobots/ajax-backed-model-behavior

environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  polymer: 1.0.0-rc.18
  dart_to_js_script_rewriter: ^1.0.1
dev_dependencies:
  polymer_elements: ^1.0.0-rc.8
  custom_element_apigen: ^0.2.1+1
  test: ^0.12.5+1
transformers:
- polymer:
    entry_points:
    - example/index.html
    - test/ajax_backed_model_behavior_test.html
    $include: test/**_test{.*,}.{dart,html}
- test/pub_serve:
    $include: test/**_test{.*,}.dart
- dart_to_js_script_rewriter
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives

